# Python Basics

# Basic Pyhton Program

In [7]:
age = 21
print("The Age is :",age)

The Age is : 21


# Loops

1. For Loop

In [14]:
for i in range(3):
  print(i)

0
1
2


2. While Loop

In [18]:
count = 1
while count <=3:
    print(count)
    count +=1

1
2
3


3. Nested Loop

In [19]:
for i in range(3):
  for j in range(4):
    print(i,j)

0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3


4. Loop With Break

In [27]:
for i in range(5):
   if i == 3:
      break
   print(i)

0
1
2


5. Loop with Continue

In [28]:
for i in range(5):
  if i == 3:
    continue
  print(i)


0
1
2
4


## **Functions**

1. Function Without Parameters

In [30]:
def weight():
    print("My weight is 65kg")
weight()

My weight is 65kg


2. Function With Parameters

In [31]:
def add(a, b):
    print(a + b)
add(2, 7)

9


3. Function With Return Value

In [32]:
def square(n):
    return n * n
result = square(3)
print(result)

9


4. Default Parameter Function

In [33]:
def greet(name="Student"):
    print("Hello", name)
greet()
greet("Masood")

Hello Student
Hello Masood


5. Keyword Arguments

In [77]:
def student(name, age):
    print(name, age)
student(age=23, name="Masood")

Masood 23


6. Lambda Function

In [78]:
square = lambda x: x*x
print(square(7))

49


## **Lists**

1. Adding a New Element at End

In [37]:
numbers = [1, 2, 3, 4]
numbers.append(5)
print(numbers)

[1, 2, 3, 4, 5]


2. Adding More than 1 Element

In [58]:
numbers = [1, 2, 3, 4]
numbers.extend([6,7])
print(numbers)

[1, 2, 3, 4, 6, 7]


3. Inserting A Number Between a List

In [39]:
numbers = [1, 2, 3, 4]
numbers.insert(1, 10)
print(numbers)

[1, 10, 2, 3, 4]


4. Removing an Element

In [40]:
numbers = [1, 2, 3, 4]
numbers.remove(3)
print(numbers)

[1, 2, 4]


5. Removing an Element using Pop

In [50]:
numbers = [1, 2, 3, 4]
numbers.pop()
print(numbers)

[1, 2, 3]


6. Finding The Index of a Number

In [59]:
numbers = [1, 2, 3, 4]
index = numbers.index(1)
print(f"The element at index {index} is: {numbers[index]}")

The element at index 0 is: 1


7. Couting the Repeated elements

In [56]:
numbers = [1, 2, 1, 4]
numbers.count(1)
print(numbers.count(1))

2


8. Sorting the List in Ascending Order

In [54]:
numbers = [2, 1, 4, 5, 3]
numbers.sort()
print(numbers)

[1, 2, 3, 4, 5]


9. Sorting the List in Descending Order

In [57]:
numbers = [1, 2, 3, 4]
numbers.reverse()
print(numbers)

[4, 3, 2, 1]


10. Coping a List

In [60]:
numbers = [1, 2, 3, 4]
new_list = numbers.copy()
print(new_list)

[1, 2, 3, 4]


11. Deleting all Elements in the List

In [49]:
numbers = [1, 2, 3, 4]
numbers.clear()
print(numbers)

[]


12. Length of a List

In [48]:
numbers = [1, 2, 3, 4]
len(numbers)

4

# **Dictionaries**

1. Creating a Dictionary

In [61]:
teacher = {"name": "Mr.Saeed", "subject": "ANN"}
print(teacher)

{'name': 'Mr.Saeed', 'subject': 'ANN'}


2. Accessing Values

In [62]:
print(teacher["name"])

Mr.Saeed


3. Adding/Updating

In [63]:
teacher["department"] = "Ai"
teacher["subject"] = "Machine Learning"

4. List to Dictionary

In [64]:
keys = ["name", "age"]
values = ["Masood", 21]
new_dict = dict(zip(keys, values))
print(new_dict)

{'name': 'Masood', 'age': 21}


5. Dictionary to List

In [65]:
dict_items = list(teacher.items())
print(dict_items)

[('name', 'Mr.Saeed'), ('subject', 'Machine Learning'), ('department', 'Ai')]


6. Dictionary with Tuples

In [66]:
locations = {(5,7): "Point A", (6,9): "Point B"}
print(locations)

{(5, 7): 'Point A', (6, 9): 'Point B'}


## **NumPy**

Importing Library

In [68]:
import numpy as np

Arrays

1. 1D Array

In [69]:
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


2. 2D Array

In [70]:
arr2 = np.array([[5, 3], [3, 5]])
print(arr2)

[[5 3]
 [3 5]]


## **2. Vectorized Operations**

In [74]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(a ** 3)
print(b ** 2)

[5 7 9]
[ 4 10 18]
[ 1  8 27]
[16 25 36]


## **3. Matrix Operations**

1. Matrix Multiplication

In [75]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


2. Broadcasting

In [76]:
a = np.array([[1, 2, 3],[4, 5, 6]])
b = np.array([10, 20, 30])
print(a + b)

[[11 22 33]
 [14 25 36]]
